ontologies:
  source:
    - url: 'https://spec.pistoiaalliance.org/idmp/ontology/MetadataIDMP/'
    - url: 'https://spec.pistoiaalliance.org/idmp/ontology/AboutIDMPDev-ReferenceIndividuals/'
  module_ignore_pattern:
    - '^(About|Metadata|Load).*'
    - 'http.*(About|Metadata).*'
  module_class_iri: 'https://spec.pistoiaalliance.org/idmp/ontology/META/ChangeManagement/Module'
  maturity_level_definition:
    - iri: 'https://spec.pistoiaalliance.org/idmp/ontology/META/ChangeManagement/Release'
      label: 'Release'
    - iri: 'https://spec.pistoiaalliance.org/idmp/ontology/META/ChangeManagement/Provisional'
      label: 'Provisional'
    - iri: 'https://spec.pistoiaalliance.org/idmp/ontology/META/ChangeManagement/Informative'
      label: 'Informative'
    - iri: 'https://spec.pistoiaalliance.org/idmp/ontology/META/ChangeManagement/Preliminary'
      label: 'Preliminary'