uc1_cq1_tests:
  sparql_template: "cq_templates/uc1_cq1.sparql"
  parameters:
    uc1_cq1_parameter_1: "<https://gsrs.ncats.nih.gov/api/v1/substances/1J444QC288>"
  expected_output: "cq_expected_results/GSRS/uc1_cq1_expected_results.json"

  uc1_cq2_tests_amlodipine:
  sparql_template: "cq_templates/uc1_cq2.sparql"
  parameters:
    uc1_cq2_parameter_1: "<https://gsrs.ncats.nih.gov/api/v1/substances/V912825CB9>"
  expected_output: "cq_expected_results/IDMP/uc1_cq2_amlodipine_expected_results.json"
