cq0_tests_amlodipine:
  sparql_template: "cq_templates/cq0.sparql"
  parameters:
    cq0_parameter_1: "Amlodipine"
  expected_output: "cq_expected_results/IDMP/cq0_amlodipine_expected_results.json"

cq0_tests_terlipressin:
  sparql_template: "cq_templates/cq0.sparql"
  parameters:
    cq0_parameter_1: "Terlipressin"
  expected_output: "cq_expected_results/IDMP/cq0_terlipressin_expected_results.json"

uc1_cq1_tests_amlodipine:
  sparql_template: "cq_templates/uc1_cq1.sparql"
  parameters:
    uc1_cq1_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/Amlodipine>"
  expected_output: "cq_expected_results/IDMP/uc1_cq1_amlodipine_expected_results.json"
uc1_cq1_tests_terlipressin:
  sparql_template: "cq_templates/uc1_cq1.sparql"
  parameters:
    uc1_cq1_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/TerlipressinExample/Terlipressin>"
  expected_output: "cq_expected_results/IDMP/uc1_cq1_terlipressin_expected_results.json"

uc1_cq2_tests_amlodipine:
  sparql_template: "cq_templates/uc1_cq2.sparql"
  parameters:
    uc1_cq2_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/AmlodipineBesylate>"
  expected_output: "cq_expected_results/IDMP/uc1_cq2_amlodipine_expected_results.json"
uc1_cq2_tests_terlipressin:
  sparql_template: "cq_templates/uc1_cq2.sparql"
  parameters:
    uc1_cq2_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/TerlipressinExample/TerlipressinAcetate>"
  expected_output: "cq_expected_results/IDMP/uc1_cq2_terlipressin_expected_results.json"

uc1_cq3_tests_amlodipine:
  sparql_template: "cq_templates/uc1_cq3.sparql"
  parameters:
    uc1_cq3_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/Amlodipine>"
  expected_output: "cq_expected_results/IDMP/uc1_cq3_amlodipine_expected_results.json"
uc1_cq3_tests_terlipressin:
  sparql_template: "cq_templates/uc1_cq3.sparql"
  parameters:
    uc1_cq3_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/TerlipressinExample/Terlipressin>"
  expected_output: "cq_expected_results/IDMP/uc1_cq3_terlipressin_expected_results.json"


uc1_cq3-1_tests_amlodipine:
  sparql_template: "cq_templates/uc1_cq3-1.sparql"
  parameters:
    uc1_cq3-1_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/AmlodipineBesylate>"
    uc1_cq3-1_parameter_2: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/Norvasc-ManufacturedItem>"
  expected_output: "cq_expected_results/IDMP/uc1_cq3-1_amlodipine_expected_results.json"
uc1_cq3-1_tests_terlipressin:
  sparql_template: "cq_templates/uc1_cq3-1.sparql"
  parameters:
    uc1_cq3-1_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/TerlipressinExample/TerlipressinAcetate>"
    uc1_cq3-1_parameter_2: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/TerlipressinExample/TerlipressinAcetateSUN-PharmaceuticalProduct>"
  expected_output: "cq_expected_results/IDMP/uc1_cq3-1_terlipressin_expected_results.json"


uc1_cq4_tests_amlodipine:
  sparql_template: "cq_templates/uc1_cq4.sparql"
  parameters:
    uc1_cq4_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/Amlodipine>"
    uc1_cq4_parameter_2: "<https://spec.pistoiaalliance.org/idmp/ontology/ISO/EuropeanJurisdiction/EuropeanRegistrationAuthorities/ExtendedEudraVigilanceMedicinalProductDictionary>"
  expected_output: "cq_expected_results/IDMP/uc1_cq4_amlodipine_expected_results.json"
uc1_cq4_tests_terlipressin:
  sparql_template: "cq_templates/uc1_cq4.sparql"
  parameters:
    uc1_cq4_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/TerlipressinExample/Terlipressin>"
    uc1_cq4_parameter_2: "<https://spec.pistoiaalliance.org/idmp/ontology/ISO/EuropeanJurisdiction/EuropeanRegistrationAuthorities/ExtendedEudraVigilanceMedicinalProductDictionary>"
  expected_output: "cq_expected_results/IDMP/uc1_cq4_terlipressin_expected_results.json"

uc1_cq5_tests_amlodipine:
  sparql_template: "cq_templates/uc1_cq5.sparql"
  parameters:
    uc1_cq5_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/EuropeanUnionClinicalTrialsRegister/AliskirenAsInvestigationalMedicinalProduct>"
  expected_output: "cq_expected_results/IDMP/uc1_cq5_amlodipine_expected_results.json"
# Missing terlipressin inputs


uc1_cq6_tests_amlodipine:
  sparql_template: "cq_templates/uc1_cq6.sparql"
  parameters:
    uc1_cq6_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/AmlodipineBesylate>"
  expected_output: "cq_expected_results/IDMP/uc1_cq6_amlodipine_expected_results.json"
# Missing terlipressin inputs


uc1_cq7_tests_amlodipine:
  sparql_template: "cq_templates/uc1_cq7.sparql"
  parameters:
    uc1_cq7_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/AmlodipineBesylate>"
  expected_output: "cq_expected_results/IDMP/uc1_cq7_amlodipine_expected_results.json"
uc1_cq7_tests_terlipressin:
  sparql_template: "cq_templates/uc1_cq7.sparql"
  parameters:
    uc1_cq7_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/TerlipressinExample/TerlipressinAcetate>"
  expected_output: "cq_expected_results/IDMP/uc1_cq7_terlipressin_expected_results.json"

# Missing amlodipine inputs
uc1_cq8_tests_terlipressin:
  sparql_template: "cq_templates/uc1_cq8.sparql"
  parameters:
    uc1_cq8_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/TerlipressinExample/TerlipressinAcetateSUN-ManufacturedItem>"
  expected_output: "cq_expected_results/IDMP/uc1_cq8_terlipressin_expected_results.json"

uc1_cq9_tests_amlodipine:
  sparql_template: "cq_templates/uc1_cq9.sparql"
  parameters:
    uc1_cq9_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/AmlodipineBesylate>"
  expected_output: "cq_expected_results/IDMP/uc1_cq9_amlodipine_expected_results.json"
uc1_cq9_tests_terlipressin:
  sparql_template: "cq_templates/uc1_cq9.sparql"
  parameters:
    uc1_cq9_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/TerlipressinExample/TerlipressinAcetate>"
  expected_output: "cq_expected_results/IDMP/uc1_cq9_terlipressin_expected_results.json"

uc2_cq1-2_tests_amlodipine:
  sparql_template: "cq_templates/uc2_cq1-2.sparql"
  parameters:
    uc2_cq1-2_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/AmlodipineBesylate>"
  expected_output: "cq_expected_results/IDMP/uc2_cq1-2_amlodipine_expected_results.json"
# Missing terlipressin inputs

uc2_cq1_tests_amlodipine:
  sparql_template: "cq_templates/uc2_cq1.sparql"
  parameters:
    uc2_cq1_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/AmlodipineBesylate>"
  expected_output: "cq_expected_results/IDMP/uc2_cq1_amlodipine_expected_results.json"
uc2_cq1_tests_terlipressin:
  sparql_template: "cq_templates/uc2_cq1.sparql"
  parameters:
    uc2_cq1_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/TerlipressinExample/TerlipressinAcetate>"
  expected_output: "cq_expected_results/IDMP/uc2_cq1_terlipressin_expected_results.json"


uc2_cq1a_tests_amlodipine:
  sparql_template: "cq_templates/uc2_cq1a.sparql"
  parameters:
    uc2_cq1a_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/AmlodipineBesylate>"
  expected_output: "cq_expected_results/IDMP/uc2_cq1a_amlodipine_expected_results.json"
# Missing terlipressin inputs

uc2_cq1b_tests_amlodipine:
  sparql_template: "cq_templates/uc2_cq1b.sparql"
  parameters:
    uc2_cq1b_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/Amlodipine>"
  expected_output: "cq_expected_results/IDMP/uc2_cq1b_amlodipine_expected_results.json"
# Missing terlipressin inputs

uc2_cq1d_tests_amlodipine:
  sparql_template: "cq_templates/uc2_cq1d.sparql"
  parameters:
    uc2_cq1d_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/PolyvinylChloride>"
  expected_output: "cq_expected_results/IDMP/uc2_cq1d_amlodipine_expected_results.json"
# Missing terlipressin inputs

uc2_cq2-1_tests_amlodipine:
  sparql_template: "cq_templates/uc2_cq2-1.sparql"
  parameters:
    uc2_cq2-1_parameter_1: "<https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/NorvascMedicinalProduct>"
  expected_output: "cq_expected_results/IDMP/uc2_cq2-1_amlodipine_expected_results.json"
# Missing terlipressin inputs

uc3_cq1-1_tests:
  sparql_template: "cq_templates/uc3_cq1-1.sparql"
  parameters:
    uc3_cq1-1_parameter_1: "10020772"
  expected_output: "cq_expected_results/IDMP/uc3_cq1-1_expected_results.json"

uc3_cq2_tests:
  sparql_template: "cq_templates/uc3_cq2.sparql"
  parameters:
    uc3_cq2_parameter_1: "10020772"
  expected_output: "cq_expected_results/IDMP/uc3_cq2_expected_results.json"  
  